[project]
name = "mcp-client-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.51.0",
    "mcp>=1.9.0",
    "openai>=1.79.0",
    "openai-agents>=0.0.15",
    "python-dotenv>=1.1.0",
]
